
services:
  pgdatabase:
    image: postgres:13
    environment:
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PG_DATABASE=${PG_DATABASE}
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
    networks:
      - airflow

# External Network configuration    
networks:
  airflow:
    external: true
    name: airflow2025_default